server:
  app_name: "Authorization service"
  port: ":8080"
  debug: true
  jwt_secret_path: "secret/private"
  jwt_public_path: "secret/public"
database:
  user: "Cracher"
  password: "123"
  host: "db"
  port: "5432"
  name: "auth_hist"
  ssl_mode: "disable"
  retries: 1
